/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiauto.view;

import guiauto.model.Alimentazione;
import guiauto.model.Auto;
import guiauto.model.Cilindrata;
import guiauto.model.Colore;
import guiauto.model.Funzioni;
import java.awt.List;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author cappellinod
 */
public class GUINuovaAuto extends javax.swing.JInternalFrame {
      
    /**
     * Creates new form GUINuovaAuto
     */
    public GUINuovaAuto() {
        initComponents();
        
        
        DefaultComboBoxModel listaCilindrata = new DefaultComboBoxModel(Cilindrata.values());
        comboboxCilindrata.setModel(listaCilindrata);
        DefaultComboBoxModel listaAlimentazione = new DefaultComboBoxModel(Alimentazione.values());
        comboboxAlimentazione.setModel(listaAlimentazione);
        DefaultComboBoxModel listaColore = new DefaultComboBoxModel(Colore.values());
        comboboxColore.setModel(listaColore);
        
        
        //String cilindrataSelezionata = comboboxCilindrata.getSelectedItem();
        //txtModello.setText(String.valueOf(cilindrataSelezionata));
        
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMarca = new javax.swing.JLabel();
        lblModello = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        checkboxTurbo = new javax.swing.JCheckBox();
        comboboxCilindrata = new javax.swing.JComboBox<>();
        lblCilindrata = new javax.swing.JLabel();
        lblAlimentazione = new javax.swing.JLabel();
        comboboxAlimentazione = new javax.swing.JComboBox<>();
        btnAddAuto = new javax.swing.JButton();
        btnChiudi = new javax.swing.JButton();
        lblColore = new javax.swing.JLabel();
        comboboxColore = new javax.swing.JComboBox<>();

        setTitle("Nuova Auto");
        setRequestFocusEnabled(false);

        lblMarca.setText("Marca:");

        lblModello.setText("Modello:");

        txtModello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelloActionPerformed(evt);
            }
        });

        checkboxTurbo.setText("Turbo");
        checkboxTurbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxTurboActionPerformed(evt);
            }
        });

        comboboxCilindrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxCilindrataActionPerformed(evt);
            }
        });

        lblCilindrata.setText("Cilindrata:");

        lblAlimentazione.setText("Alimentazione:");

        comboboxAlimentazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxAlimentazioneActionPerformed(evt);
            }
        });

        btnAddAuto.setText("Aggiungi");
        btnAddAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAutoActionPerformed(evt);
            }
        });

        btnChiudi.setText("Chiudi");
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        lblColore.setText("Colore:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlimentazione)
                            .addComponent(lblColore)
                            .addComponent(lblMarca)
                            .addComponent(lblModello)
                            .addComponent(lblCilindrata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comboboxCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkboxTurbo))
                                .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboboxColore, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboboxAlimentazione, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChiudi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModello)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCilindrata)
                    .addComponent(comboboxCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxTurbo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlimentazione))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColore)
                    .addComponent(comboboxColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAuto)
                    .addComponent(btnChiudi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelloActionPerformed

    private void comboboxCilindrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxCilindrataActionPerformed
        
        
        
        /*JComboBox<Integer> combo = (JComboBox<Integer>) evt.getSource();
        Integer cilindrataSelezionata = (Integer)combo.getSelectedItem();
        //JOptionPane.showMessageDialog(frame, "Hai selezionato "+cilindrataSelezionata );
        txtModello.setText(String.valueOf(cilindrataSelezionata));*/
    }//GEN-LAST:event_comboboxCilindrataActionPerformed

    private void checkboxTurboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxTurboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_checkboxTurboActionPerformed

    private void btnAddAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAutoActionPerformed
        
        Auto a = new Auto();
        
        
        if(!txtModello.getText().isEmpty() && !txtMarca.getText().isEmpty()) {
            a.setMarca(txtMarca.getText());
            a.setModello(txtModello.getText());
            a.setColore(Colore.valueOf(comboboxColore.getSelectedItem().toString()));
            a.setAlimentazione(Alimentazione.valueOf(comboboxAlimentazione.getSelectedItem().toString()));       
            Cilindrata cc = (Cilindrata)comboboxCilindrata.getSelectedItem(); // combobox di enum tiene oggetti di tipo enum
            a.setCilindrata(cc);
            if(checkboxTurbo.isSelected())
                a.setIsTurbo(true);
            else
                a.setIsTurbo(false);
            JOptionPane.showMessageDialog(this, "Dati dell'auto:\n\n"+a.toString(),"Nuova Auto Inserita",JOptionPane.INFORMATION_MESSAGE);
        
            ArrayList<Auto> listaAuto = new ArrayList<>();
            listaAuto.add(a);
       
            String fileName = "auto.dat";
       
            File f = new File(fileName);
            if(f.exists()){
                Funzioni.append(fileName, a);
                JOptionPane.showMessageDialog(this, "Auto aggiunta");
            }else{
            try 
            {    
                f.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "GUINuovaAuto\n\n"+ex);
            }
            
            Funzioni.write(fileName, listaAuto);
            JOptionPane.showMessageDialog(this, "Lista auto salvata");
                
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Devi inserire Marca e Modello");
        
        
        /*switch(cc){
            case MILLE:
                a.setCilindrata(Cilindrata.MILLE);
                break;
            case MILLEDUECENTO:
                a.setCilindrata(Cilindrata.MILLEDUECENTO);
                break;
            case MILLEQUATTROCENTO:
                a.setCilindrata(Cilindrata.MILLEQUATTROCENTO);
                break;
            case 1600:
                a.setCilindrata(Cilindrata.MILLESEICENTO);
                break;
            case 2000:
                a.setCilindrata(Cilindrata.DUEMILA);
                break;
                
        }*/
           
        
        
       
       
       
    }//GEN-LAST:event_btnAddAutoActionPerformed

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void comboboxAlimentazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxAlimentazioneActionPerformed
       
    }//GEN-LAST:event_comboboxAlimentazioneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuto;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JCheckBox checkboxTurbo;
    private javax.swing.JComboBox<String> comboboxAlimentazione;
    private javax.swing.JComboBox<String> comboboxCilindrata;
    private javax.swing.JComboBox<String> comboboxColore;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModello;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    // End of variables declaration//GEN-END:variables
}
