/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiauto.view;

import guiauto.model.Alimentazione;
import guiauto.model.Auto;
import guiauto.model.Cilindrata;
import guiauto.model.Colore;
import guiauto.model.Funzioni;
import static guiauto.model.Funzioni.delete;
import static guiauto.model.Funzioni.read;
import static guiauto.model.Funzioni.searchByPosition;
import static guiauto.model.Funzioni.write;
import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author cappellinod
 */
public class GUIUpdDelAuto extends javax.swing.JInternalFrame {
    
    boolean ricercariuscita = false;
    int index;
    Auto p = null;
    static final boolean DEBUG = false;
    /**
     * Creates new form GUINuovaAuto
     */
    public GUIUpdDelAuto() {
        initComponents();
        
        DefaultComboBoxModel listaCilindrata = new DefaultComboBoxModel(Cilindrata.values());
        comboboxCilindrata.setModel(listaCilindrata);
        DefaultComboBoxModel listaAlimentazione = new DefaultComboBoxModel(Alimentazione.values());
        comboboxAlimentazione.setModel(listaAlimentazione);
        DefaultComboBoxModel listaColore = new DefaultComboBoxModel(Colore.values());
        comboboxColore.setModel(listaColore);
        
        lblDEBUG_debugindex.setVisible(false);
        lblDBGIDX.setVisible(false);
        
        if(DEBUG){
            lblDEBUG_debugindex.setVisible(true);
            lblDBGIDX.setVisible(true);
        }
        
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoAzione = new javax.swing.ButtonGroup();
        lblMarca = new javax.swing.JLabel();
        lblModello = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModello = new javax.swing.JTextField();
        checkboxTurbo = new javax.swing.JCheckBox();
        comboboxCilindrata = new javax.swing.JComboBox<>();
        lblCilindrata = new javax.swing.JLabel();
        lblAlimentazione = new javax.swing.JLabel();
        comboboxAlimentazione = new javax.swing.JComboBox<>();
        btnEsegui = new javax.swing.JButton();
        lblColore = new javax.swing.JLabel();
        comboboxColore = new javax.swing.JComboBox<>();
        radioModifica = new javax.swing.JRadioButton();
        radioCancella = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroIndice = new javax.swing.JTextField();
        btnCerca = new javax.swing.JButton();
        lblDEBUG_debugindex = new javax.swing.JLabel();
        lblDBGIDX = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();

        setTitle("Modifica / Cancella Auto");
        setRequestFocusEnabled(false);

        lblMarca.setText("Marca:");

        lblModello.setText("Modello:");

        txtModello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelloActionPerformed(evt);
            }
        });

        checkboxTurbo.setText("Turbo");
        checkboxTurbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxTurboActionPerformed(evt);
            }
        });

        comboboxCilindrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxCilindrataActionPerformed(evt);
            }
        });

        lblCilindrata.setText("Cilindrata:");

        lblAlimentazione.setText("Alimentazione:");

        btnEsegui.setText("Modifica");
        btnEsegui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEseguiActionPerformed(evt);
            }
        });

        lblColore.setText("Colore:");

        gruppoAzione.add(radioModifica);
        radioModifica.setSelected(true);
        radioModifica.setText("Modifica");
        radioModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioModificaActionPerformed(evt);
            }
        });

        gruppoAzione.add(radioCancella);
        radioCancella.setText("Cancella");
        radioCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCancellaActionPerformed(evt);
            }
        });

        jLabel1.setText("Cerca:");

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        lblDEBUG_debugindex.setText("Debug index:");

        lblDBGIDX.setText("jLabel3");

        btnChiudi.setText("Chiudi");
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEsegui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDEBUG_debugindex)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDBGIDX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnChiudi))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioModifica)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAlimentazione)
                                            .addComponent(lblColore)
                                            .addComponent(lblMarca)
                                            .addComponent(lblModello)
                                            .addComponent(lblCilindrata))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(comboboxColore, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(comboboxAlimentazione, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(radioCancella)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(comboboxCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(checkboxTurbo))
                                                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(txtNumeroIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnCerca))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioModifica)
                    .addComponent(radioCancella))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModello)
                    .addComponent(txtModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCilindrata)
                    .addComponent(comboboxCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxTurbo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxAlimentazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlimentazione))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColore)
                    .addComponent(comboboxColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsegui)
                    .addComponent(lblDEBUG_debugindex)
                    .addComponent(lblDBGIDX)
                    .addComponent(btnChiudi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelloActionPerformed

    private void comboboxCilindrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxCilindrataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxCilindrataActionPerformed

    private void checkboxTurboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxTurboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxTurboActionPerformed

    private void btnEseguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEseguiActionPerformed
           String fileName = "auto.dat";
           ArrayList<Auto> list = Funzioni.read(fileName);
           if(radioModifica.isSelected()) //
           {
                if(!txtModello.getText().isEmpty() && !txtMarca.getText().isEmpty()) {
                    p.setMarca(txtMarca.getText());
                    p.setModello(txtModello.getText());   
                    p.setColore(Colore.valueOf(comboboxColore.getSelectedItem().toString()));
                    p.setAlimentazione(Alimentazione.valueOf(comboboxAlimentazione.getSelectedItem().toString()));       
                    Cilindrata cc = (Cilindrata)comboboxCilindrata.getSelectedItem(); // combobox di enum tiene oggetti di tipo enum
                    p.setCilindrata(cc);
             
                    if(checkboxTurbo.isSelected())
                        p.setIsTurbo(true);
                    else
                        p.setIsTurbo(false);
            
                    int index = Integer.parseInt(txtNumeroIndice.getText());
            
                    if(list.set(index, p) != null){
                    write(fileName, list);
           
                    JOptionPane.showMessageDialog(this, "Dati dell'auto:\n\n"+p.toString(),"Auto Modificata",JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(this, "Update completato!");   
                    }
                }
                else
                    JOptionPane.showMessageDialog(this, "Devi inserire Marca e Modello");
           
           }  
           else{ //Seguono azioni per cancellazione
               try{
               
               lblDBGIDX.setText(String.valueOf(index)); //componente di debug, attivare cambiando DEBUG su true
               index = Integer.parseInt(txtNumeroIndice.getText());
               lblDBGIDX.setText(String.valueOf(index));
                if(delete(fileName, list, index) != null){
                    JOptionPane.showMessageDialog(this, "Eliminazione completata!");
                    txtMarca.setText("");
                    txtModello.setText("");
                    checkboxTurbo.setSelected(false);
                    }
                else
                    JOptionPane.showMessageDialog(this, "Eliminazione non riuscita!");
               }catch(IndexOutOfBoundsException ex){
                    JOptionPane.showMessageDialog(this, index +" è fuori lista !");
               }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex);
        }
           }        
    }//GEN-LAST:event_btnEseguiActionPerformed

    private void radioCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCancellaActionPerformed
        txtMarca.setEnabled(false);
        txtModello.setEnabled(false);
        comboboxCilindrata.setEnabled(false);
        comboboxAlimentazione.setEnabled(false);
        comboboxColore.setEnabled(false);
        checkboxTurbo.setEnabled(false);
        btnEsegui.setText("Cancella");
    }//GEN-LAST:event_radioCancellaActionPerformed

    private void radioModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioModificaActionPerformed
        txtMarca.setEnabled(true);
        txtModello.setEnabled(true);
        comboboxCilindrata.setEnabled(true);
        comboboxAlimentazione.setEnabled(true);
        comboboxColore.setEnabled(true);
        checkboxTurbo.setEnabled(true);
        btnEsegui.setText("Modifica");
        
    }//GEN-LAST:event_radioModificaActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        String fileName = "auto.dat";
        ArrayList<Auto> listaAuto = Funzioni.read(fileName);
        
        
        try{
        index = Integer.parseInt(txtNumeroIndice.getText());
        lblDBGIDX.setText(String.valueOf(index));
        p = searchByPosition(index, fileName);
        
            if(listaAuto != null) {
                
                txtMarca.setText(p.getMarca());
                txtModello.setText(p.getModello());
                if(p.isIsTurbo())
                    checkboxTurbo.setSelected(true);
                else
                    checkboxTurbo.setSelected(false);
                
                comboboxCilindrata.setSelectedItem(p.getCilindrata());
                comboboxAlimentazione.setSelectedItem(p.getAlimentazione());
                comboboxColore.setSelectedItem(p.getColore());
                ricercariuscita = true;
                
            }
        }catch(IndexOutOfBoundsException ex){
                JOptionPane.showMessageDialog(this, index + " è fuori lista !");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnChiudiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnChiudi;
    private javax.swing.JButton btnEsegui;
    private javax.swing.JCheckBox checkboxTurbo;
    private javax.swing.JComboBox<String> comboboxAlimentazione;
    private javax.swing.JComboBox<String> comboboxCilindrata;
    private javax.swing.JComboBox<String> comboboxColore;
    private javax.swing.ButtonGroup gruppoAzione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblColore;
    private javax.swing.JLabel lblDBGIDX;
    private javax.swing.JLabel lblDEBUG_debugindex;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModello;
    private javax.swing.JRadioButton radioCancella;
    private javax.swing.JRadioButton radioModifica;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModello;
    private javax.swing.JTextField txtNumeroIndice;
    // End of variables declaration//GEN-END:variables
}
