/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiauto.view;

import guiauto.model.Auto;
import guiauto.model.Funzioni;
import static guiauto.model.Funzioni.searchByPosition;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cappellinod
 */
public class GUIVisualizzaAuto extends javax.swing.JInternalFrame {
    
    boolean ricercariuscita = false;
    Auto p = null;
    int index;
    StringBuilder sb;
    String file = "auto.dat";
    /**
     * Creates new form GUIVisualizzaAuto
     */
    public GUIVisualizzaAuto() {
        initComponents();
        
        
        
        
        ArrayList<Auto> listaAuto = Funzioni.read(file);
        
        sb = new StringBuilder();
        
        if(listaAuto != null){
            for (Auto auto : listaAuto) {
                sb.append(auto.toString() + "\n"+"\n");
            }
            textAllAuto.setText(sb.toString());
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroIndice = new javax.swing.JTextField();
        btnSalvaAuto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAllAuto = new javax.swing.JTextArea();
        btnAggiorna = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setTitle("Visualizza Auto");

        jLabel1.setText("Cerca x ID:");

        txtNumeroIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIndiceActionPerformed(evt);
            }
        });

        btnSalvaAuto.setText("Salva in Tutte_le_Auto.txt");
        btnSalvaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaAutoActionPerformed(evt);
            }
        });

        jButton1.setText("Chiudi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        textAllAuto.setColumns(20);
        textAllAuto.setRows(5);
        jScrollPane1.setViewportView(textAllAuto);

        btnAggiorna.setText("Aggiorna");
        btnAggiorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiornaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvaAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAggiorna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvaAuto)
                    .addComponent(jButton1)
                    .addComponent(btnCerca)
                    .addComponent(btnAggiorna))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIndiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIndiceActionPerformed

    private void btnSalvaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaAutoActionPerformed
        if(!ricercariuscita){
        //mettere per salvaggio arraylist in txt
        String exportfilename = "Tutte_le_Auto.txt";
        
        //Funzioni.maketxt(exportfilename);
        try{
        Funzioni.writetxt(exportfilename,sb.toString()); //non convince come salva sb.toString() su schermo è ben fatto su file no
            JOptionPane.showMessageDialog(this, "Salvataggio Riuscito");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        }
        else{
            String exportfilename = index+"_"+p.getMarca()+"_"+p.getModello()+".txt";
            //Funzioni.maketxt(exportfilename);
            try{
            Funzioni.writetxt(exportfilename,p.toString());
                JOptionPane.showMessageDialog(this, "Salvataggio Riuscito");
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex);
            }
        }//mettere per salvataggio singola auto txt
    }//GEN-LAST:event_btnSalvaAutoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        
        String fileName = "auto.dat";
        ArrayList<Auto> listaAuto = Funzioni.read(fileName);
        
        
        try{
        index = Integer.parseInt(txtNumeroIndice.getText());
        p = searchByPosition(index, fileName);
        
            if(listaAuto != null) {
                
                textAllAuto.setText(p.toString());
                String exportfilename = index+"_"+p.getMarca()+"_"+p.getModello()+".txt";
                btnSalvaAuto.setText("Salva in "+exportfilename);
                ricercariuscita = true;
                
            }
        }catch(IndexOutOfBoundsException ex){
                JOptionPane.showMessageDialog(this, "Fuori Lista !");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnAggiornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiornaActionPerformed
        
        ArrayList<Auto> listaAuto = Funzioni.read(file);
        
        sb = new StringBuilder();
        if(listaAuto != null){
            for (Auto auto : listaAuto) {
                sb.append(auto.toString() + "\n"+"\n");
            }
            textAllAuto.setText(sb.toString());
        }
        String exportfilename = "Tutte_le_auto.txt";
        btnSalvaAuto.setText("Salva in "+exportfilename);
        ricercariuscita = false;
    }//GEN-LAST:event_btnAggiornaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiorna;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnSalvaAuto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAllAuto;
    private javax.swing.JTextField txtNumeroIndice;
    // End of variables declaration//GEN-END:variables
}
